config/routes.rb
Rails.application.routes.draw do
  resources :events do
    get  :join, to: 'events#join', as: 'join'
    get  :accept_request, to: 'events#accept_request', as: 'accept_request'
    get  :reject_request, to: 'events#reject_request', as: 'reject_request'
  end
  
  get  :my_events, to: 'events#my_events', as: 'my_events'
  get "home/index"
  devise_for :users
  get 'tags/:tag', to: 'events#index', as: :tag

  root 'events#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base

	belongs_to :event
	belongs_to :user

	validates :user_id, :uniqueness => {:scope => :event_id}

	scope :pending, -> {where(state: 'request_sent')}
	scope :accepted, -> {where(state: 'accepted')}
	scope :rejected, -> {where(state: 'rejected')}

	include Workflow

	workflow_column :state

	workflow do
		state :request_sent do
			event :accept, :transitions_to => :accepted
			event :reject, :transitions_to => :rejected
		end
		state :accepted
		state :rejected
	end

	def self.join_event(user_id, event_id, state)
		self.create(user_id: user_id, event_id: event_id, state: state)
	end

end

app/models/event.rb
class Event < ActiveRecord::Base

	extend FriendlyId
  	friendly_id :title, use: :slugged

	belongs_to :organizers, class_name: "User"

	has_many :taggings
  	has_many :tags, through: :taggings

	has_many :attendences
	has_many :users, :through => :attendances

	def self.tagged_with(name)
		Tag.find_by_name!(name).events
	end

	def self.tag_counts
		Tag.select("tags.id, tags.name, count(taggings.tag_id) as count").
		joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
	end

	def all_tags=(names)
		self.tags = names.split(",").map do |n|
			Tag.where(name: n.strip).first_or_create!
		end
	end

	def all_tags
    	tags.map(&:name).join(", ")
    end

	def event_owner(organizer_id)
		User.find_by(id: organizer_id)
	end

	def self.pending_requests(event_id)
		Attendance.where(event_id: event_id, state: 'request_sent')
	end

	def self.show_accepted_attendees(event_id)
		Attendance.where(event_id: event_id, state: 'accepted')
	end
	
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
  	has_many :events, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	 	:recoverable, :rememberable, :trackable, :validatable

	has_many :attendences
	has_many :events, :through => :attendances
	has_many :organized_events, class_name: "Event", foreign_key: "organizer_id"      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :set_event, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy, :join]
	before_action :event_owner!, only: [:edit, :update, :destroy, :accept, :reject]
	respond_to :html, :json
 

	# GET /events
	# GET /events.json
	def index
		if params[:tag]
			@events = Event.tagged_with(params[:tag])
		else
			@events = Event.all
		end
	end

	# GET /events/1
	# GET /events/1.json
	def show
		@event_owner = @event.event_owner(@event.organizer_id)
		@pending_requests = Attendance.with_request_sent_state.where(event_id: @event.id)
		@attendees = Attendance.with_accepted_state.where(event_id: @event.id)
		@going = @attendees.where(user_id: current_user.id)
	end

	# GET /events/new
	def new
		@event = Event.new
	end

	def my_events
		@event_owner = User.find_by(id: current_user.id)
		@events = Event.where(organizer_id: current_user.id)
	end

	# GET /events/1/edit
	def edit
	end

	# POST /events
	# POST /events.json
	def create
		@event = current_user.organized_events.new(event_params)

		respond_to do |format|
			if @event.save
				format.html { redirect_to @event, notice: 'Event was successfully created.' }
				format.json { render :show, status: :created, location: @event }
			else
				format.html { render :new }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /events/1
	# PATCH/PUT /events/1.json
	def update
		respond_to do |format|
			if @event.update(event_params)
				format.html { redirect_to @event, notice: 'Event was successfully updated.' }
				format.json { render :show, status: :ok, location: @event }
			else
				format.html { render :edit }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /events/1
	# DELETE /events/1.json
	def destroy
		@event.destroy
		respond_to do |format|
			format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def tag_cloud
		@tags = Event.tag_counts_on(:tags)
	end

	def join
		@attendance = Attendance.join_event(current_user.id, params[:event_id], 'request_sent')
		'Request Sent' if @attendance.save
		redirect_to events_url
		#respond_with(@attendance)
	end

	def accept_request
		@event = Event.find(params[:event_id])
		@attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
		@attendance.accept!
		'Applicant Accepted' if @attendance.save
		redirect_to events_url
		#respond_with(@attendance)
	end

	def reject_request
		@event = Event.find(params[:event_id])
		@attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
		@attendance.reject!
		'Applicant Rejected' if @attendance.save
		redirect_to events_url
		#respond_with(@attendance)
	end

  	private
  	
	# Use callbacks to share common setup or constraints between actions.
	def set_event
		@event = Event.friendly.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def event_params
		params.require(:event).permit(:title, :star_date, :end_date, :location, :agenda, :address, :organizer_id, :all_tags, :user_id)
	end

	def event_owner!
		if @event.organizer_id != current_user.id
			redirect_to events_path
			flash[:notice] = 'You do not have enough permissions to do this'
		end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size - 1)
			yield(tag, classes[index.round])
		end
	end
	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		"http://gravatar.com/avatar/#{gravatar_id}.png"
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
	<% if @event.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
			<ul>
				<% @event.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="input-group input-group-sm">
		<%= f.label :title %><br>
		<%= f.text_field :title, :class => "form-control" %>
	</div>
	<div class="field">
		<%= f.label :star_date %><br>
		<%= f.datetime_select :star_date %>
	</div>
	<div class="field">
		<%= f.label :end_date %><br>
		<%= f.datetime_select :end_date %>
	</div>
	<div cclass="input-group input-group-sm">  
		<%= f.label :all_tags, "List All Tags, separate each tag by a comma" %><br />
		<%= f.text_field :all_tags, :class => "form-control"  %>
	</div>
	<div class="input-group input-group-sm">
		<%= f.label :location %><br>
		<%= f.text_field :location, :class => "form-control"  %>
	</div>
	<div class="field">
		<%= f.label :address %><br>
		<%= f.text_area :address %>
	</div>
	<div class="field">
		<%= f.label :agenda %><br>
		<%= f.text_area :agenda, :cols => 50, :rows => 10 %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/events/_tag_cloud.html.erb
<div class="col-lg-4">
	<h3>Search Tags</h3>  
	<div>
		<% tag_cloud Event.tag_counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
			<%= link_to tag.name, tag_path(tag.name), class: css_class %>
		<% end %>	
	</div>
</div>

app/views/events/edit.html.erb
<div class="container">
	<div class="jumbotron">
		<h1>Editing Event</h1>
	</div>
</div>	
<div class="container">
	<%= render 'form' %>

	<%= link_to 'Show', @event %> |
	<%= link_to 'Back', events_path %>
</div>	

app/views/events/index.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<%= image_tag("melbourne1.jpg", :class => "first-slide") %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Events.</h1>
					<p>Ne eum commodo intellegebat, inermis elaboraret contentiones eam in, ea eos eruditi offendit. Per ex adhuc augue, cu vis erat primis. Elitr labore voluptua ei usu, id eum eruditi reformidans. Vitae probatus ullamcorper eam ex.</p>
					<p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
				</div>
			</div>
		</div>
		<div class="item">
			<%= image_tag("melbourne2.jpg", :class => "second-slide") %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Follow us.</h1>
					<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
					<p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
				</div>
			</div>
		</div>
		<div class="item">
			<%= image_tag("melbourne4.jpg", :class => "third-slide") %>
			<div class="container">
				<div class="carousel-caption">
					<h1>One more for good measure.</h1>
						<p>Vel ad solum ceteros sadipscing. Est magna populo docendi ne, modus euismod cum ei. Nec vitae tollit democritum at. Ut nam mazim quidam, his insolens oportere ea..</p>
						<p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
					</div>
				</div>
			</div>
		</div>
		<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div><!-- /.carousel -->


 	<div class="jumbotron">
     	<div class="container">
	        <h1>The best events</h1>
	        <p>Lorem ipsum dolor sit amet, simul debitis vituperatoribus et cum, cu everti sanctus quo. Diceret nusquam temporibus mei cu, ne duo atomorum pertinacia. Docendi delicata te est, errem dissentias vim ne. At saperet scaevola vis. His virtute inermis no, vel ea nominavi democritum, laboramus abhorreant voluptatibus vim at. In pro voluptua detraxit definitionem, eu usu stet perfecto lobortis..</p>
     	</div>
	</div>

<div class="container">
	<h2>Search Tags</h2>  
		<% tag_cloud Event.tag_counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
			<%= link_to tag.name, tag_path(tag.name), class: css_class %>
		<% end %>  
	<br/>
	<br/>
	<%= link_to 'Create an Event', new_event_path, :class=>"btn btn-default btn-primary" %>
	<br/>
	<h2>Recently Created Events</h2> 
	<div class="row">
		<% @events.each do |event| %>
			<div class="col-xs-6 col-lg-4">
				<div class="thumbnail">
					<div class="caption">
						<h3><%= event.title %></h3> 
						<label>Start Date:</label>
						<%if event.star_date.present?%>
							<%= l event.star_date, :format => :date_format %>
						<%end%> 
						<br/>
						<label>End Date:</label>
						<%if event.end_date.present?%>
							<%= l event.end_date, :format => :date_format %>
						<%end%>
						<br/>
						<label>Location: </label><%= event.location %>
						<br/>
						<label>Organized By:</label>
						<br/>
						<%@event_owner = event.event_owner(event.organizer_id)%>
						<br/>
						<%= image_tag avatar_url(@event_owner) %>
						<%= @event_owner.email %>
						<br/>
						<br/>
						<label>Tags:</label><br/>
						<%=raw event.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %><br/><br/>

						<%= link_to 'Show Details', event, :class=>"btn btn-info btn-small" %>
						<% if user_signed_in? && event.organizer_id == current_user.id%>
							<%= link_to 'Edit', edit_event_path(event), :class=>"btn btn-primary btn-small" %>
							<%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-small" %>
						<%end%><br/><br/>
					</div>
				</div>	
			</div>
		<% end %>
	</div>
</div>

app/views/events/my_events.html.erb
<div class="container">
    <%= render "tag_cloud"%>
    <br/>
    <%= link_to 'Create an Event', new_event_path, :class=>"btn btn-default btn-primary" %>
    <br/>
    <h1>Recently Created Events</h1>  
    <div class="row">       
        <% @events.each do |event| %>
            <div class="col-xs-6 col-lg-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3><%= event.title %></h3>  
                        <label>Start Date:</label><%= l event.star_date, :format => :date_format %>
                        <br/>
                        <label>End Date:</label><%= l event.end_date, :format => :date_format %>
                        <br/>
                        <label>Location:</label><%= event.location %>
                        <br/>
                        <label>Address:</label>
                        <address>
                        <%= event.address %><br/>
                        </address>
                        <label>Agenda:</label>
                        <%= event.agenda %>
                        <br/>
                        <br/>
                        <label>Organized By:</label>
                        <br/>
                        <%= image_tag avatar_url(@event_owner) %>
                        <%= @event_owner.email %>
                        <br/>
                        <br/>
                        <!-- Display Tags-->
                        <label>Tags:</label><br/>
                        <%=raw event.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
                        <br/>
                        <br/>
                        <%= link_to 'Show Details', event, :class=>"btn btn-info btn-small" %>
                        <% if user_signed_in? && event.organizer_id == current_user.id %>
                        <%= link_to 'Edit', edit_event_path(event), :class=>"btn btn-primary btn-small" %>
                        <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-small" %>
                        <%end%>
                        <br/><br/>
                    </div>
                </div>
            </div>
        <% end %>
     </div>
   
 </div>   

app/views/events/new.html.erb
<div class="container">
	<div class="jumbotron">
		<h1>New Event</h1>
	</div>
</div>	
<div class="container">
	<%= render 'form' %>
	<%= link_to 'Back', events_path %>
</div>	

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
	<h1><%= @event.title %></h1>
	<br>
	<p>
		<strong>Start date:</strong>
		<%= @event.star_date %>
	</p>
	<p>
		<strong>End Date:</strong>
		<%= @event.end_date %>
	</p>
	<p>
		<strong>Location:</strong>
		<%= @event.location %>
	</p>
	<p>
		<strong>Agenda:</strong>
		<%= @event.agenda %>
	</p>
	<p>
		<strong>Address:</strong>
		<%= @event.address %>
	</p>
	<p>
		<strong>Tags:</strong>
		<%=raw @event.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
	</p>
</div>

<% if user_signed_in? && @event.organizer_id == current_user.id %>
	<label>Join Requests</label>
	<% if @pending_requests.present? %>
		<div class="row">
			<% @pending_requests.each do |p| %>
				<div class="col-xs-6 col-lg-4">
					<div class="thumbnail">
						<div class="caption">
							<%= image_tag avatar_url(p.user) %>
							<%= p.user.email%>
							<%= link_to 'Accept', event_accept_request_path(:event_id => @event.id, :attendance_id => p.id), :class=>"btn btn-success btn-small" %>
							<%= link_to 'Reject', event_reject_request_path(:event_id => @event.id, :attendance_id => p.id), :class=>"btn btn-danger btn-small" %>
						</div>
					</div>
				</div>	
			<%end%>
		</div>
	<%else%>
		<p>No Pending Requests for this event</p>
	<%end%>
<%end%>

<br/>

<label>Attendees</label>
<div class="row">
	<% @attendees.each do |a|%>
		<div class="col-xs-6 col-lg-4">
			<div class="thumbnail">
				<div class="caption">
					<%= image_tag avatar_url(a.user) %>
					<%= a.user.email%>
				</div>
			</div>
		</div>	
	<%end%>
</div>

<strong>Organizer:</strong>
<div class="row">
	<div class="col-xs-6 col-lg-4">
		<div class="thumbnail">
			<div class="caption">
				<%= image_tag avatar_url(@event_owner) %>
				<%= @event_owner.email %>
			</div>
		</div>
	</div>
</div>	

<br/>

<% if @going.empty? && @event.organizer_id != current_user.id %>
	<%= link_to "Join", event_join_path(:event_id => @event.id), :class=>"btn btn-success btn-small" %>
<%end%>
<%= link_to 'All Events', events_path, :class=>"btn btn-info btn-small" %>
<% if user_signed_in? && @event.organizer_id == current_user.id %>
	<%= link_to 'Edit', edit_event_path(@event), :class=>"btn btn-primary btn-small" %>
	<%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-small" %>
<%end%>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventstr</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-static-top">
		<div class="container">
				<ul class="nav navbar-nav">
					<li><%= link_to "Events", events_path %></li>
					<% if user_signed_in? %>
						<li class="active"><%= link_to "My Events", my_events_path %></li>
					<%end%>
				</ul>
				<ul class="nav navbar-nav pull-right">
					<% if user_signed_in? %>
						<li><%= link_to "#{current_user.email}" %></li>
						<li class="active"><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
					<%else%>
						<li><%= link_to "Login", new_user_session_path %></li>
						<li class="active"><%= link_to "SignUp", new_user_registration_path %></li>
					<%end%>
				</ul>
		</div>
	</div>
    <div class="container">
      <%= yield %>
    </div> 

</body>
</html>